using UnityEngine;

public class BubbleRefill : MonoBehaviour
{
    public float refillAmount = 20f;

    [Header("–í—Å–ø–ª—ã—Ç–∏–µ –ø—É–∑—ã—Ä—è")]
    public float riseSpeed = 0.5f; // —Å–∫–æ—Ä–æ—Å—Ç—å –≤—Å–ø–ª—ã—Ç–∏—è –≤–≤–µ—Ä—Ö

    private void Update()
    {
        // –º–µ–¥–ª–µ–Ω–Ω–æ–µ –≤—Å–ø–ª—ã—Ç–∏–µ –≤–≤–µ—Ä—Ö
        transform.Translate(Vector2.up * riseSpeed * Time.deltaTime);
    }

  private void OnTriggerEnter2D(Collider2D other)
{
    if (other.CompareTag("Player") && BreathingManager.Instance != null)
    {
        BreathingManager.Instance.RefillBreath(refillAmount);
        Debug.Log("ü´ß –ü—É–∑—ã—Ä—å –≤–æ—Å—Å—Ç–∞–Ω–æ–≤–∏–ª –¥—ã—Ö–∞–Ω–∏–µ –Ω–∞ " + refillAmount + "%");
        Destroy(gameObject);
    }
}
}